import { InstrumentConfig, TimeframeId } from './types';

export const INSTRUMENTS: InstrumentConfig[] = [
  // FOREX
  {
    symbol: 'EURUSD',
    name: 'Euro / US Dollar',
    category: 'FOREX',
    decimals: 5,
    pipSize: 0.0001,
    contractMultiplier: 100000,
    defaultPrice: 1.0865,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 0.8,
    description: 'Major currency pair with tight spread and high liquidity.',
    change24h: 0.24,
    high24h: 1.0892,
    low24h: 1.0841,
    isFavorite: true,
  },
  {
    symbol: 'GBPUSD',
    name: 'British Pound / US Dollar',
    category: 'FOREX',
    decimals: 5,
    pipSize: 0.0001,
    contractMultiplier: 100000,
    defaultPrice: 1.2740,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 1.1,
    description: 'The Cable: volatile major currency pair with great trend structure.',
    change24h: -0.15,
    high24h: 1.2785,
    low24h: 1.2710,
    isFavorite: true,
  },
  {
    symbol: 'USDJPY',
    name: 'US Dollar / Japanese Yen',
    category: 'FOREX',
    decimals: 3,
    pipSize: 0.01,
    contractMultiplier: 100000,
    defaultPrice: 154.25,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 0.9,
    description: 'Asian session cornerstone with clean liquidity sweeps and momentum.',
    change24h: 0.42,
    high24h: 154.80,
    low24h: 153.90,
    isFavorite: true,
  },
  {
    symbol: 'AUDUSD',
    name: 'Australian Dollar / US Dollar',
    category: 'FOREX',
    decimals: 5,
    pipSize: 0.0001,
    contractMultiplier: 100000,
    defaultPrice: 0.6655,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 1.0,
    description: 'Commodity-linked major pair with distinct session movements.',
    change24h: 0.18,
    high24h: 0.6685,
    low24h: 0.6630,
  },
  {
    symbol: 'USDCAD',
    name: 'US Dollar / Canadian Dollar',
    category: 'FOREX',
    decimals: 5,
    pipSize: 0.0001,
    contractMultiplier: 100000,
    defaultPrice: 1.3680,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 1.2,
    description: 'North American currency pair influenced by crude oil trends.',
    change24h: -0.08,
    high24h: 1.3710,
    low24h: 1.3650,
  },
  {
    symbol: 'USDCHF',
    name: 'US Dollar / Swiss Franc',
    category: 'FOREX',
    decimals: 5,
    pipSize: 0.0001,
    contractMultiplier: 100000,
    defaultPrice: 0.9020,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    spreadPips: 1.0,
    description: 'Safe-haven currency pair with key macro correlations.',
    change24h: 0.05,
    high24h: 0.9055,
    low24h: 0.8995,
  },

  // COMMODITIES
  {
    symbol: 'XAUUSD',
    name: 'Gold / US Dollar',
    category: 'COMMODITIES',
    decimals: 2,
    pipSize: 0.1,
    contractMultiplier: 100,
    defaultPrice: 2385.40,
    minLot: 0.01,
    maxLot: 20,
    lotStep: 0.01,
    spreadPips: 1.8,
    description: 'High-volatility precious metal, popular for day trading and scalp setups.',
    change24h: 1.12,
    high24h: 2402.50,
    low24h: 2370.20,
    isFavorite: true,
  },
  {
    symbol: 'XAGUSD',
    name: 'Silver / US Dollar',
    category: 'COMMODITIES',
    decimals: 3,
    pipSize: 0.01,
    contractMultiplier: 5000,
    defaultPrice: 29.65,
    minLot: 0.01,
    maxLot: 20,
    lotStep: 0.01,
    spreadPips: 2.0,
    description: 'Precious metal with strong momentum cycles and explosive breakout ranges.',
    change24h: 0.85,
    high24h: 30.15,
    low24h: 29.20,
  },
  {
    symbol: 'USOIL',
    name: 'WTI Crude Oil',
    category: 'COMMODITIES',
    decimals: 2,
    pipSize: 0.01,
    contractMultiplier: 1000,
    defaultPrice: 78.40,
    minLot: 0.01,
    maxLot: 25,
    lotStep: 0.01,
    spreadPips: 2.5,
    description: 'Global energy benchmark with London and New York session volume spikes.',
    change24h: -1.35,
    high24h: 79.80,
    low24h: 77.90,
    isFavorite: true,
  },

  // CRYPTO
  {
    symbol: 'BTCUSD',
    name: 'Bitcoin / US Dollar',
    category: 'CRYPTO',
    decimals: 2,
    pipSize: 1.0,
    contractMultiplier: 1,
    defaultPrice: 64500.00,
    minLot: 0.01,
    maxLot: 10,
    lotStep: 0.01,
    spreadPips: 12.0,
    description: 'Leading cryptocurrency asset trading 24/7 with deep order flow dynamics.',
    change24h: 2.45,
    high24h: 65800.00,
    low24h: 63200.00,
    isFavorite: true,
  },
  {
    symbol: 'ETHUSD',
    name: 'Ethereum / US Dollar',
    category: 'CRYPTO',
    decimals: 2,
    pipSize: 0.1,
    contractMultiplier: 1,
    defaultPrice: 3480.00,
    minLot: 0.01,
    maxLot: 20,
    lotStep: 0.01,
    spreadPips: 1.5,
    description: 'Major smart-contract crypto asset with high intraday beta and clear levels.',
    change24h: 1.80,
    high24h: 3550.00,
    low24h: 3410.00,
    isFavorite: true,
  },
  {
    symbol: 'SOLUSD',
    name: 'Solana / US Dollar',
    category: 'CRYPTO',
    decimals: 2,
    pipSize: 0.05,
    contractMultiplier: 1,
    defaultPrice: 148.50,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    spreadPips: 0.2,
    description: 'High-speed layer 1 crypto token with rapid swings and high volatility.',
    change24h: 4.12,
    high24h: 154.20,
    low24h: 142.10,
  },

  // INDICES
  {
    symbol: 'NAS100',
    name: 'US Tech 100 Index (Nasdaq)',
    category: 'INDICES',
    decimals: 2,
    pipSize: 1.0,
    contractMultiplier: 20,
    defaultPrice: 18650.00,
    minLot: 0.1,
    maxLot: 50,
    lotStep: 0.1,
    spreadPips: 1.5,
    description: 'Top US tech index with active New York market open opening ranges (ORB).',
    change24h: 0.95,
    high24h: 18780.00,
    low24h: 18510.00,
    isFavorite: true,
  },
  {
    symbol: 'US30',
    name: 'Wall Street 30 Index (Dow)',
    category: 'INDICES',
    decimals: 1,
    pipSize: 1.0,
    contractMultiplier: 5,
    defaultPrice: 39420.0,
    minLot: 0.1,
    maxLot: 50,
    lotStep: 0.1,
    spreadPips: 2.0,
    description: 'Blue-chip industrial index with powerful session momentum and trend follow.',
    change24h: 0.40,
    high24h: 39590.0,
    low24h: 39280.0,
    isFavorite: true,
  },
  {
    symbol: 'SPX500',
    name: 'US 500 Index (S&P 500)',
    category: 'INDICES',
    decimals: 2,
    pipSize: 0.25,
    contractMultiplier: 50,
    defaultPrice: 5490.50,
    minLot: 0.1,
    maxLot: 50,
    lotStep: 0.1,
    spreadPips: 0.5,
    description: 'Premier global equity benchmark with high liquidity and structural zones.',
    change24h: 0.62,
    high24h: 5515.00,
    low24h: 5460.00,
  },
  {
    symbol: 'GER40',
    name: 'Germany 40 Index (DAX)',
    category: 'INDICES',
    decimals: 1,
    pipSize: 1.0,
    contractMultiplier: 25,
    defaultPrice: 18320.0,
    minLot: 0.1,
    maxLot: 50,
    lotStep: 0.1,
    spreadPips: 1.2,
    description: 'Leading European stock index driven by Frankfurt and London cash sessions.',
    change24h: -0.32,
    high24h: 18450.0,
    low24h: 18240.0,
  }
];

export const TIMEFRAMES: { id: TimeframeId; label: string; seconds: number; isIntraday?: boolean }[] = [
  { id: '1m', label: '1m', seconds: 60, isIntraday: true },
  { id: '2m', label: '2m', seconds: 120, isIntraday: true },
  { id: '3m', label: '3m', seconds: 180, isIntraday: true },
  { id: '5m', label: '5m', seconds: 300, isIntraday: true },
  { id: '15m', label: '15m', seconds: 900, isIntraday: true },
  { id: '30m', label: '30m', seconds: 1800, isIntraday: true },
  { id: '1H', label: '1H', seconds: 3600, isIntraday: true },
  { id: '2H', label: '2H', seconds: 7200, isIntraday: true },
  { id: '4H', label: '4H', seconds: 14400, isIntraday: true },
  { id: '1D', label: '1D', seconds: 86400, isIntraday: false },
  { id: '1W', label: '1W', seconds: 604800, isIntraday: false },
];

export const getInstrumentConfig = (symbol: string): InstrumentConfig => {
  return INSTRUMENTS.find(i => i.symbol === symbol) || INSTRUMENTS[0];
};
