export interface MetricDefinition {
  id: string;
  name: string;
  category: string;
  description: string;
  unit: 'currency' | 'percent' | 'number' | 'ratio' | 'duration' | 'days';
  defaultChartType: 'line' | 'area' | 'bar' | 'green_red_bar' | 'stacked_bar';
  isCumulative?: boolean;
}

export interface MetricCategory {
  id: string;
  name: string;
  metrics: MetricDefinition[];
}

export const METRIC_CATEGORIES: MetricCategory[] = [
  {
    id: 'time_analysis',
    name: '1. Time Analysis',
    metrics: [
      {
        id: 'logged_days_cum',
        name: 'Logged days - cumulative',
        category: 'Time Analysis',
        description: 'Cumulative count of active trading days logged over time',
        unit: 'days',
        defaultChartType: 'line',
        isCumulative: true,
      },
      {
        id: 'avg_trading_days_duration_cum',
        name: 'Average trading days duration - cumulative',
        category: 'Time Analysis',
        description: 'Cumulative average daily trading active session duration',
        unit: 'duration',
        defaultChartType: 'line',
        isCumulative: true,
      },
      {
        id: 'avg_hold_time_cum',
        name: 'Average hold time - cumulative',
        category: 'Time Analysis',
        description: 'Cumulative average trade holding duration in minutes',
        unit: 'duration',
        defaultChartType: 'area',
        isCumulative: true,
      },
      {
        id: 'longest_trade_duration_cum',
        name: 'Longest trade duration - cumulative',
        category: 'Time Analysis',
        description: 'Maximum single trade holding time recorded up to date',
        unit: 'duration',
        defaultChartType: 'line',
        isCumulative: true,
      },
      {
        id: 'max_trading_days_duration_cum',
        name: 'Max trading days duration - cumulative',
        category: 'Time Analysis',
        description: 'Maximum consecutive active trading days streak',
        unit: 'days',
        defaultChartType: 'line',
        isCumulative: true,
      },
    ],
  },
  {
    id: 'profitability',
    name: '2. Profitability',
    metrics: [
      {
        id: 'net_pnl',
        name: 'Net P&L',
        category: 'Profitability',
        description: 'Net realized profit and loss after fees and commissions',
        unit: 'currency',
        defaultChartType: 'green_red_bar',
      },
      {
        id: 'gross_profit',
        name: 'Gross Profit',
        category: 'Profitability',
        description: 'Total dollar gains from winning trades',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'gross_loss',
        name: 'Gross Loss',
        category: 'Profitability',
        description: 'Total dollar losses from losing trades',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'avg_win',
        name: 'Average Win',
        category: 'Profitability',
        description: 'Mean profit earned on winning trades',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'avg_loss',
        name: 'Average Loss',
        category: 'Profitability',
        description: 'Mean loss incurred on losing trades',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'win_rate',
        name: 'Win Rate',
        category: 'Profitability',
        description: 'Percentage of closed trades resulting in a profit',
        unit: 'percent',
        defaultChartType: 'line',
      },
      {
        id: 'loss_rate',
        name: 'Loss Rate',
        category: 'Profitability',
        description: 'Percentage of closed trades resulting in a loss',
        unit: 'percent',
        defaultChartType: 'line',
      },
      {
        id: 'profit_factor',
        name: 'Profit Factor',
        category: 'Profitability',
        description: 'Gross Profit divided by Gross Loss',
        unit: 'ratio',
        defaultChartType: 'line',
      },
      {
        id: 'expectancy',
        name: 'Expectancy',
        category: 'Profitability',
        description: 'Expected dollar return per trade based on win rate and reward-to-risk',
        unit: 'currency',
        defaultChartType: 'line',
      },
      {
        id: 'avg_net_trade_pnl',
        name: 'Average Net Trade P&L',
        category: 'Profitability',
        description: 'Average profit or loss per executed trade',
        unit: 'currency',
        defaultChartType: 'green_red_bar',
      },
      {
        id: 'cumulative_pnl',
        name: 'Cumulative P&L',
        category: 'Profitability',
        description: 'Running account equity balance growth from realized trades',
        unit: 'currency',
        defaultChartType: 'area',
        isCumulative: true,
      },
      {
        id: 'daily_pnl',
        name: 'Daily P&L',
        category: 'Profitability',
        description: 'Net realized P&L grouped by trading date',
        unit: 'currency',
        defaultChartType: 'green_red_bar',
      },
      {
        id: 'r_multiple',
        name: 'R-Multiple',
        category: 'Profitability',
        description: 'Total risk-adjusted return units generated',
        unit: 'ratio',
        defaultChartType: 'green_red_bar',
      },
      {
        id: 'avg_r_multiple',
        name: 'Average R-Multiple',
        category: 'Profitability',
        description: 'Average R-multiple captured per trade',
        unit: 'ratio',
        defaultChartType: 'line',
      },
    ],
  },
  {
    id: 'risk_drawdown',
    name: '3. Risk & Drawdown',
    metrics: [
      {
        id: 'max_drawdown',
        name: 'Max Drawdown',
        category: 'Risk & Drawdown',
        description: 'Peak-to-trough equity dollar drawdown',
        unit: 'currency',
        defaultChartType: 'area',
        isCumulative: true,
      },
      {
        id: 'current_drawdown',
        name: 'Current Drawdown',
        category: 'Risk & Drawdown',
        description: 'Distance in dollars from the all-time peak balance',
        unit: 'currency',
        defaultChartType: 'area',
        isCumulative: true,
      },
      {
        id: 'drawdown_pct',
        name: 'Drawdown %',
        category: 'Risk & Drawdown',
        description: 'Percentage depth below highest equity peak',
        unit: 'percent',
        defaultChartType: 'area',
        isCumulative: true,
      },
      {
        id: 'avg_drawdown',
        name: 'Average Drawdown',
        category: 'Risk & Drawdown',
        description: 'Average depth across all drawdown periods',
        unit: 'currency',
        defaultChartType: 'line',
      },
      {
        id: 'risk_per_trade',
        name: 'Risk per Trade',
        category: 'Risk & Drawdown',
        description: 'Dollar amount risked per trade based on stop loss distance',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'avg_risk',
        name: 'Average Risk',
        category: 'Risk & Drawdown',
        description: 'Mean initial risk dollar value per trade',
        unit: 'currency',
        defaultChartType: 'line',
      },
      {
        id: 'largest_loss',
        name: 'Largest Loss',
        category: 'Risk & Drawdown',
        description: 'Single largest losing trade in dollars',
        unit: 'currency',
        defaultChartType: 'bar',
      },
      {
        id: 'largest_win',
        name: 'Largest Winning Trade',
        category: 'Risk & Drawdown',
        description: 'Single largest winning trade in dollars',
        unit: 'currency',
        defaultChartType: 'bar',
      },
    ],
  },
  {
    id: 'trading_activity',
    name: '4. Trading Activity & Volume',
    metrics: [
      {
        id: 'total_trades',
        name: 'Total Trades',
        category: 'Trading Activity & Volume',
        description: 'Number of trade executions closed in period',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'trades_per_day',
        name: 'Trades per Day',
        category: 'Trading Activity & Volume',
        description: 'Average trade execution frequency per active trading day',
        unit: 'number',
        defaultChartType: 'line',
      },
      {
        id: 'winning_trades',
        name: 'Winning Trades',
        category: 'Trading Activity & Volume',
        description: 'Count of trades closed with a positive net P&L',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'losing_trades',
        name: 'Losing Trades',
        category: 'Trading Activity & Volume',
        description: 'Count of trades closed with a negative net P&L',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'breakeven_trades',
        name: 'Break-even Trades',
        category: 'Trading Activity & Volume',
        description: 'Count of trades closed with exactly $0 P&L',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'trading_volume',
        name: 'Trading Volume',
        category: 'Trading Activity & Volume',
        description: 'Total contracts or shares traded in period',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'avg_daily_volume',
        name: 'Average Daily Volume',
        category: 'Trading Activity & Volume',
        description: 'Mean daily contracts/shares traded',
        unit: 'number',
        defaultChartType: 'line',
      },
      {
        id: 'contracts_quantity',
        name: 'Contracts / Quantity',
        category: 'Trading Activity & Volume',
        description: 'Total execution volume in position units',
        unit: 'number',
        defaultChartType: 'bar',
      },
      {
        id: 'long_vs_short',
        name: 'Long vs Short Trades',
        category: 'Trading Activity & Volume',
        description: 'Comparison of Long (BUY) vs Short (SELL) position counts',
        unit: 'number',
        defaultChartType: 'stacked_bar',
      },
    ],
  },
  {
    id: 'streaks_consistency',
    name: '5. Streaks & Consistency',
    metrics: [
      {
        id: 'current_win_streak',
        name: 'Current Win Streak',
        category: 'Streaks & Consistency',
        description: 'Consecutive winning trades at current snapshot',
        unit: 'number',
        defaultChartType: 'line',
      },
      {
        id: 'current_loss_streak',
        name: 'Current Loss Streak',
        category: 'Streaks & Consistency',
        description: 'Consecutive losing trades at current snapshot',
        unit: 'number',
        defaultChartType: 'line',
      },
      {
        id: 'longest_win_streak',
        name: 'Longest Win Streak',
        category: 'Streaks & Consistency',
        description: 'Maximum consecutive winning trades streak recorded',
        unit: 'number',
        defaultChartType: 'line',
        isCumulative: true,
      },
      {
        id: 'longest_loss_streak',
        name: 'Longest Loss Streak',
        category: 'Streaks & Consistency',
        description: 'Maximum consecutive losing trades streak recorded',
        unit: 'number',
        defaultChartType: 'line',
        isCumulative: true,
      },
      {
        id: 'consecutive_winning_days',
        name: 'Consecutive Winning Days',
        category: 'Streaks & Consistency',
        description: 'Max consecutive green trading days',
        unit: 'days',
        defaultChartType: 'line',
      },
      {
        id: 'consecutive_losing_days',
        name: 'Consecutive Losing Days',
        category: 'Streaks & Consistency',
        description: 'Max consecutive red trading days',
        unit: 'days',
        defaultChartType: 'line',
      },
      {
        id: 'consistency_score',
        name: 'Consistency Score',
        category: 'Streaks & Consistency',
        description: 'Statistical score (0-100) based on return stability and rule discipline',
        unit: 'percent',
        defaultChartType: 'line',
      },
      {
        id: 'green_days',
        name: 'Green Days',
        category: 'Streaks & Consistency',
        description: 'Total count of profitable trading days',
        unit: 'days',
        defaultChartType: 'bar',
      },
      {
        id: 'red_days',
        name: 'Red Days',
        category: 'Streaks & Consistency',
        description: 'Total count of losing trading days',
        unit: 'days',
        defaultChartType: 'bar',
      },
    ],
  },
];

export const ALL_METRICS_MAP = new Map<string, MetricDefinition>(
  METRIC_CATEGORIES.flatMap(cat => cat.metrics).map(m => [m.id, m])
);

export function getMetricById(id: string): MetricDefinition {
  const found = ALL_METRICS_MAP.get(id);
  if (found) return found;
  // Fallback if id not found
  return {
    id,
    name: id,
    category: 'General',
    description: 'Custom trading metric',
    unit: 'number',
    defaultChartType: 'line',
  };
}
