import React, { useState } from 'react';
import { RefreshCw, FileText, Clipboard, Check } from 'lucide-react';

interface TradingPlanTemplateCalcProps {
  onClose: () => void;
}

export const TradingPlanTemplateCalc: React.FC<TradingPlanTemplateCalcProps> = ({ onClose }) => {
  // Plan State
  const [traderName, setTraderName] = useState('TradeForge Elite');
  const [tradingStyle, setTradingStyle] = useState('Day Trading');
  const [assetClasses, setAssetClasses] = useState('Futures & Forex');
  const [maxRisk, setMaxRisk] = useState('1.0');
  const [dailyLoss, setDailyLoss] = useState('3.0');
  const [maxDrawdown, setMaxDrawdown] = useState('6.0');
  const [setups, setSetups] = useState('HTF Golden Pocket Fibonacci Retracements, VWAP Deviation Bands');
  const [sizingRules, setSizingRules] = useState('Fractional Kelly (0.25 Sizing) adjusted dynamically.');

  const [copied, setCopied] = useState(false);

  const handleReset = () => {
    setTraderName('TradeForge Elite');
    setTradingStyle('Day Trading');
    setAssetClasses('Futures & Forex');
    setMaxRisk('1.0');
    setDailyLoss('3.0');
    setMaxDrawdown('6.0');
    setSetups('HTF Golden Pocket Fibonacci Retracements, VWAP Deviation Bands');
    setSizingRules('Fractional Kelly (0.25 Sizing) adjusted dynamically.');
    setCopied(false);
  };

  // Compile full markdown template
  const compiledPlan = `====================================================================
INSTITUTIONAL RISK BOUNDS & GENERAL TRADING PLAN
Generated by TradeForge Pro Sizing Platform
====================================================================

Trader Name     : ${traderName}
Trading Style   : ${tradingStyle}
Asset Classes   : ${assetClasses}

--------------------------------------------------------------------
1. CORE RISK CONTROLS & DESK PARAMETERS
--------------------------------------------------------------------
* Maximum Risk Per Single Trade : ${maxRisk}% of Account Equity
* Intraday Daily Stop-Loss Limit : ${dailyLoss}% of Account Equity
* Maximum Historical Drawdown Limit : ${maxDrawdown}% of Account Equity
  (Breaching the drawdown limit mandates an immediate halt on risk capital)

--------------------------------------------------------------------
2. SIZING PROTOCOLS & POSITION CONTROLS
--------------------------------------------------------------------
* Position Sizing Rule:
  ${sizingRules}

--------------------------------------------------------------------
3. CONFLUENCE SETUPS & EXECUTION PROCEDURES
--------------------------------------------------------------------
* Active Strategies:
  ${setups}

* Execution Checklist:
  [ ] HTF Bias determined and aligned
  [ ] High Impact news parsed and scheduled
  [ ] Position size verified via TradeForge sizing calculator
  [ ] Stop-Loss and Take-Profits set before placing the trade
  [ ] Emotional discipline and rules adherence checked

====================================================================
This trading plan represents an binding agreement with yourself.
Strict adherence to risk parameters is the hallmark of professional success.
====================================================================`;

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(compiledPlan);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left: Interactive Form Inputs */}
        <div className="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 font-mono">Plan Parameters</h4>
            <button
              onClick={handleReset}
              className="text-[10px] flex items-center gap-1 text-indigo-400 hover:text-indigo-300 font-semibold uppercase tracking-wider font-mono"
            >
              <RefreshCw className="w-3 h-3" /> Reset Template
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="text-xs text-slate-400 mb-1 block">Trader Name / Handle</label>
              <input
                type="text"
                value={traderName}
                onChange={(e) => setTraderName(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Trading Style</label>
              <input
                type="text"
                value={tradingStyle}
                onChange={(e) => setTradingStyle(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Asset Classes</label>
              <input
                type="text"
                value={assetClasses}
                onChange={(e) => setAssetClasses(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Max Risk Per Trade (%)</label>
              <input
                type="number"
                step="0.1"
                value={maxRisk}
                onChange={(e) => setMaxRisk(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs font-mono text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Daily Loss Limit (%)</label>
              <input
                type="number"
                step="0.5"
                value={dailyLoss}
                onChange={(e) => setDailyLoss(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs font-mono text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="col-span-2">
              <label className="text-xs text-slate-400 mb-1 block">Max Cumulative Drawdown (%)</label>
              <input
                type="number"
                step="0.5"
                value={maxDrawdown}
                onChange={(e) => setMaxDrawdown(e.target.value)}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs font-mono text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="col-span-2">
              <label className="text-xs text-slate-400 mb-1 block">Core Setups & Trigger Confluences</label>
              <textarea
                value={setups}
                onChange={(e) => setSetups(e.target.value)}
                rows={2}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500 resize-none"
              />
            </div>

            <div className="col-span-2">
              <label className="text-xs text-slate-400 mb-1 block">Sizing Rules</label>
              <textarea
                value={sizingRules}
                onChange={(e) => setSizingRules(e.target.value)}
                rows={2}
                className="w-full rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500 resize-none"
              />
            </div>
          </div>
        </div>

        {/* Right: Compiled Plan Live View */}
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 font-mono">Live Document Preview</h4>
            <button
              onClick={handleCopyToClipboard}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                copied 
                  ? 'bg-emerald-600/20 border border-emerald-500/50 text-emerald-400' 
                  : 'bg-indigo-600/20 border border-indigo-500/30 text-indigo-400 hover:bg-indigo-600/30'
              }`}
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5" /> Plan Copied!
                </>
              ) : (
                <>
                  <Clipboard className="w-3.5 h-3.5" /> Copy Plan to Clipboard
                </>
              )}
            </button>
          </div>

          <div className="p-4 bg-slate-900 border border-slate-800 rounded-2xl h-[340px] overflow-y-auto font-mono text-[10px] text-slate-300 whitespace-pre-wrap leading-relaxed shadow-inner">
            {compiledPlan}
          </div>
        </div>
      </div>
    </div>
  );
};
